### ISSUE TITLE
Error in `_rate_limit`.

### ISSUE THREAD

**Issue by AAA3A-AAA3A** [tn3w/flask_Captchaify#4]
Hello,

Sorry, I'm still here. 😅 I got this error now. I've had a look, and it seems that a `data/tea_emojis.json` file is missing.
```
Exception on /static/assets/js/plugins/utils.js [GET]
Traceback (most recent call last):
  File "/home/.../.local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/.../.local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/.../.local/lib/python3.10/site-packages/flask/app.py", line 868, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/.../.local/lib/python3.10/site-packages/flask/app.py", line 1243, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/.../.local/lib/python3.10/site-packages/flask_Captchaify/__init__.py", line 353, in _rate_limit
    emoji = random.choice(TEA_EMOJIS)
  File "/usr/local/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
KeyError: 0
```

Thanks in advance,
Have a nice evening.

**Comment by tn3w** [comment]
Thank you for disclosing this issue. 
The error occurred when renaming the file from `teaemojis.json` to `tea_emojis.json`. The file was apparently not uploaded again. All assets files including this file have now been moved to the assets folder. This should fix the error and make the project tidier.

With version 1.6.2 this bug has been fixed
To see all the changes click here: https://github.com/tn3w/flask_Captchaify/compare/2cd41680ef11b9cf63aa7578873755e70e70ad0f...63ac99e1a7ba27550844aee22fab25a08ab1e7fb
